// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/app_data_local.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3249005922053616154),
      name: 'AppDataLocal',
      lastPropertyId: const obx_int.IdUid(7, 7035501483545002961),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7719699339539903407),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8413255323379683920),
            name: 'generatedValue',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4489705238928648647),
            name: 'displayedValue',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5032662397944092641),
            name: 'difficulty',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2879626010504958223),
            name: 'startTime',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2322962183713057259),
            name: 'endTime',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7035501483545002961),
            name: 'result',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 3249005922053616154),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [4777508910651133619],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        4622647948351672378,
        1801482463922178401,
        4876996100416411958,
        4667084497766903013,
        7756581303899129286,
        2327537258555817781,
        1372909495533054680,
        2738814095453169913
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AppDataLocal: obx_int.EntityDefinition<AppDataLocal>(
        model: _entities[0],
        toOneRelations: (AppDataLocal object) => [],
        toManyRelations: (AppDataLocal object) => {},
        getId: (AppDataLocal object) => object.id,
        setId: (AppDataLocal object, int id) {
          object.id = id;
        },
        objectToFB: (AppDataLocal object, fb.Builder fbb) {
          final generatedValueOffset = object.generatedValue == null
              ? null
              : fbb.writeString(object.generatedValue!);
          final displayedValueOffset = object.displayedValue == null
              ? null
              : fbb.writeString(object.displayedValue!);
          final difficultyOffset = object.difficulty == null
              ? null
              : fbb.writeString(object.difficulty!);
          final resultOffset =
              object.result == null ? null : fbb.writeString(object.result!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, generatedValueOffset);
          fbb.addOffset(2, displayedValueOffset);
          fbb.addOffset(3, difficultyOffset);
          fbb.addInt64(4, object.startTime);
          fbb.addInt64(5, object.endTime);
          fbb.addOffset(6, resultOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AppDataLocal()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..generatedValue = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..displayedValue = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..difficulty = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..startTime =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12)
            ..endTime =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14)
            ..result = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppDataLocal] entity fields to define ObjectBox queries.
class AppDataLocal_ {
  /// See [AppDataLocal.id].
  static final id =
      obx.QueryIntegerProperty<AppDataLocal>(_entities[0].properties[0]);

  /// See [AppDataLocal.generatedValue].
  static final generatedValue =
      obx.QueryStringProperty<AppDataLocal>(_entities[0].properties[1]);

  /// See [AppDataLocal.displayedValue].
  static final displayedValue =
      obx.QueryStringProperty<AppDataLocal>(_entities[0].properties[2]);

  /// See [AppDataLocal.difficulty].
  static final difficulty =
      obx.QueryStringProperty<AppDataLocal>(_entities[0].properties[3]);

  /// See [AppDataLocal.startTime].
  static final startTime =
      obx.QueryIntegerProperty<AppDataLocal>(_entities[0].properties[4]);

  /// See [AppDataLocal.endTime].
  static final endTime =
      obx.QueryIntegerProperty<AppDataLocal>(_entities[0].properties[5]);

  /// See [AppDataLocal.result].
  static final result =
      obx.QueryStringProperty<AppDataLocal>(_entities[0].properties[6]);
}
